using erlichlab                               # obviously the tests use the Calculus module... 
using Base.test                              # and the Base.test module... 
tests = ["finite_differerence", ...          # the test file names are stored as strings... 
for t in tests
   include("$(t).jl")                         # ... so that they can be evaluated in a loop 
end
